# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcname', models.CharField(max_length=32)),
                ('dcname', models.CharField(max_length=32)),
                ('cluster', models.CharField(max_length=32)),
                ('hostip', models.CharField(max_length=32)),
                ('vmname', models.CharField(max_length=100)),
                ('vmip', models.CharField(max_length=16)),
                ('vmmacc', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=16)),
                ('vmpath', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vmlist',
            unique_together=set([('vmname', 'vmmacc')]),
        ),
    ]
