---
component:
  #  appdbpatch:
  #    pools:
  #      - SQ1DMZ
  #      - SASB
  #    version:
  #      33.9.0-0000
  #    boxlist:
  #      - SQ1DMZ: CONFIGDB_PRI.SQ1DMZ.oradbsqsvr001
  #      - SASB: CONFIGDB_PRI.SASB.oradbsasrv001

  #  j2ee:
  #    pools:
  #      #- jsq1
  #      - jsa1
  #    version:
  #      33.9.0-0000
  #
  #  meetingjoinservice:
  #    pools:
  #      - jsq1
  #      - jsa1
  #    version:
  #      2.8.0-0100

  #  meetingregistryservice:
  #    pools:
  #      - vsq1
  #      - vsa1
  #    version:
  #      1.26.0-0100

  #  clustermrs:
  #    pools:
  #      - jsq1
  #      - jsa1
  #    version:
  #      1.19.0-0100
  #
  #  webng:
  #    pools:
  #      - jsq1
  #      - jsa1
  #    version:
  #      1.14.0-0100

  #  reminder:
  #    pools:
  #      - rsq1
  #      - jsa1
  #    version:
  #      3.28.0-0000

  #  authentication:
  #    pools:
  #      - wasq1
  #      - wasa1
  #    version:
  #      2.20.0-0100

  #  superadmin:
  #    pools:
  #      - cfgsq1
  #      - cfgsa1
  #    version:
  #      33.9.0-0000

  #  eureka:
  #    pools:
  #      - sq1
  #      - ed1sm
  #      - ed12sa
  #      - esa
  #      - esg
  #      - ed1sb
  #    version:
  #      5.12.0-0000
  #
  #  mmp:
  #    pools:
  #      - sq1
  #      - gmsg11
  #      - m11sm
  #      - msa1
  #      - m31sb
  #    version:
  #      5.5.0-0000
  #
  #  nbr:
  #    pools:
  #      - sq1
  #      - nsa1
  #    version:
  #      4.3.0-0000

  #  tahoe:
  #    pools:
  #      - tsq1
  #      - tsq2
  #      - tsa1
  #    version:
  #      4.8.0-0100
  #
  #  tpgw:
  #    pools:
  #      - vsq1
  #      - vsg1
  #      - vsa1
  #    version:
  #      5.12.0-0000

  #  cms:
  #    pools:
  #      - tsq1
  #      - tsq2
  #      - tsq1givr
  #      - tsq2givr
  #      - tsa1
  #    version:
  #      2.6.0-0000

  #  givr:
  #    pools:
  #      - tsq1
  #      - tsq2
  #      - tsg1
  #      - tsa1
  #    version:
  #      2.8.0-0100
  #
  #  xmlapi:
  #    pools:
  #      #- sq1
  #      - xsa1
  #    version:
  #      7.22.0-0000
  #
  #  gla:
  #    pools:
  #      - sq1
  #      - vsa1
  #    version:
  #      3.14.0-0000
  #
  #  csp:
  #    pools:
  #      - cspsq1
  #      - gcspsg1
  #      - cspdf1
  #      - cspia1
  #    version:
  #      1.4.0-0000

  globalpageservice:
    pools:
      - gpsq1
    version:
      1.3.0-0100

#  signservice:
#    pools:
#      - jsq1
#    version:
#      1.0.0-0100
#  tsp:
#    pools:
#      - pt1
#    version:
#      3.21.0-0001